CREATE DATABASE `example_minions`;

CREATE TABLE minions(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
town_id INT,
CONSTRAINT fk_minions_towns
FOREIGN KEY (town_id)
REFERENCES towns(id)
);

CREATE TABLE towns(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL
);
